receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  hostmetrics:
    collection_interval: 5m
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      system:

processors:
  batch:
    timeout: 1s
  memory_limiter:
    limit_mib: 4096
    check_interval: 5s
    spike_limit_mib: 512
  resourcedetection:
    detectors: ["system"]

exporters:
  otlp/aspire:
    endpoint: "localhost:14317"
    tls:
      insecure: true
  otlp/grafana:
    endpoint: "localhost:24317"
    tls:
      insecure: true

connectors:
  dito:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces/default:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [dito, otlp/aspire, otlp/grafana]
    traces/dito:
      receivers: [dito]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [otlp/aspire, otlp/grafana]
    metrics/dito:
      receivers: [dito]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [otlp/aspire, otlp/grafana]
    metrics/default:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [otlp/aspire, otlp/grafana]
    logs/default:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/aspire, otlp/grafana]
