# Due to me unable to reach the aspire dashboard from a container started by aspire, a docker-compose file is used.
services:
  dito:
    image: xoechz/dito:latest
    volumes:
      - ./collector-config-demo.yaml:/etc/dito/config.yaml
    command: ["--config", "/etc/dito/config.yaml"]
    network_mode: host